server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #  ignored-services: microservicecloud-dept
  #  忽略原来真实的微服务名字, 只能使用映射路径访问
  ignored-services: "*"
  prefix: /miaoqi
  routes:
    mydept:
      path: /mydept/**
      serviceId: microservicecloud-dept # 就是spring.application.name

info:
  app.name: miaoqi-microcloud
  company.name: www.miaoqi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

