spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: miaoqi
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 9999